#!/usr/bin/env bash
cd RXApi
echo -e "\e[33m           R\e[0m"
echo -e "\e[33m           X\e[0m"
echo -e "\e[33m           A\e[0m"
echo -e "\e[33m           p\e[0m"
echo -e "\e[33m           i\e[0m"
while(true) do
lua start.lua 
done
